from flask import Flask, render_template, request

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/diagnose', methods=['POST'])
def diagnose():
    # Get form data
    name = request.form['name']
    age = request.form['age']
    gender = request.form['gender']
    weight = float(request.form['weight'])
    hb = float(request.form['hb'])
    bp = int(request.form['bp'])

    # Analyze data
    weight_message = "You are healthy, don't worry!" if weight < 110 else "You are overweight."
    hb_message = "You are not anemic." if hb > 12 else "You are anemic."
    bp_message = "You are not hypertensive." if bp < 120 else "You are hypertensive."

    result = {
        'name': name,
        'age': age,
        'gender': gender,
        'weight_message': weight_message,
        'hb_message': hb_message,
        'bp_message': bp_message
    }

    return render_template('result.html', result=result)

if __name__ == '__main__':
    app.run(debug=True)
